### ISSUE TITLE
setDtr/setRTS is not implemented for FTDI imll

### ISSUE THREAD

**Issue by mik3y** [mik3y/usb-serial-for-android#13]
_From [d...@antonsmirnov.name](https://code.google.com/u/117735236346327365583/) on March 16, 2013 23:18:49_

What steps will reproduce the problem? 1. invoke setDtr/setRts (true) What is the expected output? What do you see instead? Expected it to set to true, but nothing happens What version of the product are you using? On what operating system? Please provide any additional information below. Just not implemented in FtdiSerialDriver class

_Original issue: http://code.google.com/p/usb-serial-for-android/issues/detail?id=13_

**Comment by egueli** [comment]
The code above works also for Parallax RFID reader (https://www.parallax.com/product/28340): it needs to be enabled before reading tag IDs.

**Comment by aroller** [comment]
I would benefit from the [setRTS method][2] being implemented when communicating with the iRobot Create 2.  [See this exchange][1].  

[1]: http://robotics.stackexchange.com/questions/7895/irobot-create-2-powering-up-after-sleep
[2]:https://github.com/mik3y/usb-serial-for-android/blob/a213f06ad0b19fd6f1a6b4f8b2f74f986a00ea68/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/FtdiSerialDriver.java

**Comment by mik3y** [comment]
I'm hoping to spend some time this weekend given this project some much needed love. Help (especially in the form of ready-to-go-PRs) would be very welcome, either on this issue or others!

**Comment by aroller** [comment]
Mike, that's great.  I'm more of a high level programmer, but I'm happy to help where I can.  The specs for the [iRobot Create 2][1] is the primary source. I'm just learning it now myself.  Here is the excerpt that relates to the BRC pin:

>In Passive mode, Roomba will go into power saving mode to conserve battery power after five minutes of inactivity. To disable sleep, pulse the BRC pin low periodically before these five minutes expire. Each pulse resets this five minute counter. (One example that would not cause the baud rate to inadvertently change is to pulse the pin low for one second, every minute, but there are other periods and duty cycles that would work, as well.) 

So perhaps pulsing pin 5 (BRC) is capable now without the setRTS feature enabled?  If so, please provide some instructions and I will make an attempt with the current library snapshot.  

Per Steve on Robotics Stack Exchange, who's [profile][2] shows he helped launch the Create 2,  I won't need to send a pulse if the Ready to Send state is enabled (since the iRobot provided cable does some magic apparently).  So using the RTS would be the preferred method.

My goal is actually to wake it up rather than keep it awake, however, it would seem the RTS feature would assist with that too.

I realize this information may not be that helpful to you mostly due to my lack of understanding serial communications protocol.  Steve could provide more insight than me, but once you have a snapshot I'd be happy to test and debug the implementation.

Again, thanks for the very useful library. 




[1]: http://www.irobot.com/~/media/MainSite/PDFs/About/STEM/Create/create_2_Open_Interface_Spec.pdf
[2]: http://robotics.stackexchange.com/users/7665/steve

**Comment by kai-morich** [comment]
solved with #118
