### ISSUE TITLE
Support for ft312d

### ISSUE THREAD

**Issue by crapthings** [mik3y/usb-serial-for-android#89]
Would we support ft31x ?

**Comment by srd1** [comment]
Hey,

I am Srijan from IIT Bombay, Undergraduate in Electrical Engineering. I am working on a project that needs to communicate to the Android and I have chosen FT312D for the UART protocol. As you know, this chip is made for this application.

The hardware schematic is consistent with the development boards and datasheet served by FTDI. I am trying to run primarily using this app - https://play.google.com/store/apps/details?id=com.ftdi.ft31x.hyperterm&hl=en

As I plug in the board into the Android (Kitkat) and open the app, there is the option of "Setting" where one is supposed to configure the UART. I get this error/notification "Need to connect to cable and allow USB permission". The message pops up even if no board is connected, suggesting that the IC is not getting detected or enumerated.

Having experience on the same, I would appreciate your help to get me a lead on this in any way possible.

**Comment by atomsndbytes** [comment]
hey srijan,
try checking if your device supports otg , because for the vcp to work we need to otg driver/mux to be present on the phone hardware , plus you will have to check the phones USB permissions , as vcp is not a directly broadcasted service , but normally the USB permissions error will occur if you haven't declared access to the port in your ,gradle file .



Sent from my Mi phoneOn Srijan Dhare <notifications@github.com>, Aug 10, 2015 10:07 PM wrote:Hey,

I am Srijan from IIT Bombay, Undergraduate in Electrical Engineering. I am working on a project that needs to communicate to the Android and I have chosen FT312D for the UART protocol. As you know, this chip is made for this application.

The hardware schematic is consistent with the development boards and datasheet served by FTDI. I am trying to run primarily using this app - https://play.google.com/store/apps/details?id=com.ftdi.ft31x.hyperterm&hl=en

As I plug in the board into the Android (Kitkat) and open the app, there is the option of "Setting" where one is supposed to configure the UART. I get this error/notification "Need to connect to cable and allow USB permission". The message pops up even if no board is connected, suggesting that the IC is not getting detected or enumerated.

Having experience on the same, I would appreciate your help to get me a lead on this in any way possible.

**Comment by kai-morich** [comment]
FT31x is unlikely to be supported, use FT321 instead
